# Generated by Django 5.2.5 on 2025-08-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_remove_estudiante_cursos_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
