# Generated by Django 5.2.5 on 2025-08-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_programa_codigo_programa_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='creditos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
